### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by jsta** [jsta/limnojobs#2]
* [x] ECOLOG
    * [x] Set up email delivery
    * [x] Code email parsing
    * [x] Code email filtering
 * [x] RSS feeds
 * [x] Web scraping
 * [x] Google sheets
 * [x] Set up logging
 * [x] Set up tweeting/command-line ops

**Comment by jsta** [comment]
Investigate `gspread` package for reading from google sheets
